### ISSUE TITLE
What difference is there between your and andres-montanez versions?

### ISSUE THREAD

**Issue by TheRatG** [magephp/magallanes#2]
Hello, could you describe what did you enhance here?
https://github.com/andres-montanez/Magallanes

**Comment by benr77** [comment]
Yes, is there an explanation at all? This repo isn't even shown as a fork of the original project. Any info at all would be useful.

Thanks

**Comment by jeffreymb** [comment]
:+1:

**Comment by DenisMir** [comment]
I would be interested in the differences as well.

**Comment by iooK** [comment]
+1

**Comment by zf2timo** [comment]
I am also interested in a clarification. I think one of the project should be marked as abandoned on packagist.

**Comment by hectornguyen** [comment]
Hello everyone,
I am so sorry about the lately response to this issue since I didn't pay much attention to GitHub at all.

Let me explain about this,
As we already know, https://github.com/andres-montanez/Magallanes is not actively and also not documented very well.
I didn't fork from that repo because I'm aiming to convert the whole code into Symfony 2 Console which I'm using for all project I have.

It is under-development heavily (lot of lovely bugs) and yes, time is very expensive to me. 7 months to answer to this ticket...

I do apologise once again for the delay and hope I can release it soon.
Thanks for asking.

Hector.

**Comment by zf2timo** [comment]
Thank you for your Response and the clarification, @hectornguyen. 
To avoid confusion of other people, i think this should be noted at the top of the README.md
