### ISSUE TITLE
Old releases are not deleted

### ISSUE THREAD

**Issue by DavidGarciaCat** [magephp/magallanes#8]
Hey there,

I have realised that given my current user (it is `ubuntu`) is not the same than the one that runs the web server (that is `www-data`) old releases remains in the system because I cannot delete them.

Checking the `ReleaseTask.php` built-in command I can see this:
```
foreach ($releasesToDelete as $releaseIdToDelete) {
    $directoryToDelete = $releasesDirectory . '/' . $releaseIdToDelete;
    if ($directoryToDelete != '/') {
        $command = 'rm -rf ' . $directoryToDelete;
        $this->runCommandRemote($command);
    }
}
```

Do you think that we can add a modifier to run the command as `root` user:
`$command = 'sudo rm -rf ' . $directoryToDelete;`

Maybe something like this?
```
# other environment settings

extras:
  # other extra settings
  use-sudo: true # Boolean, false by default
```
So if we have added the new `use-sudo` and is `true` we can run all shell commands as a `root` user?

Your impressions?

**Comment by hectornguyen** [comment]
Hi @DavidGarciaCat,
My advise when you use any deployment tool like this is, you should specifie the webserver user all the time, (in your case www-data). Then you give it few permissions to be access from SSH or something else, but it should never granted `sudo` permission for security permission.

This is quite basic thing in DevOps world :) Deploy user never has `sudo` permission!

If you need further information, please let me know.
Thank you.

**Comment by DavidGarciaCat** [comment]
Hi @hectornguyen 

I understand your point, but then looks like this tool has a blocker. If we check - for example - `capifony` we can set the `use_sudo` parameter in config file.

From my POV `www-data` - that is a System user and it manages the web server - should not have login access via SSH. So I assume the only option is to set a new PHP-FPM Pool (to manage the source code of my project using my deployment user - `ubuntu` - instead of `www-data`).

Cheers,

**Comment by hectornguyen** [comment]
Hi @DavidGarciaCat 

Because in my point, that `use_sudo` is unecessary and  if any men who able to use deployment tool should be a `sysadmin`, so they always have a way to deal with this.

In our world, we will create a new user like `deploy`, give them permission to group `www-data` or whatever, create new sudoers NOPASSWD for `deploy` in `/etc/sudoers.d/` with specified commands and we are done.

This is not blocker of the tool honestly, it is a question if we really try to configure our server or not. Implement new functions for something can be done by shell commands makes me sick.

I use this tool because it integrated easlity to any CI, it also means all my commits are deployed automatically when ever I release them. I customised my server previously quite hard to do something like:
- New user located at /srv/users/autopilot (I DO HATE /home, /var/www they don't make any senses to me)
- Custom build apache, nginx, mysql, php-fpm (5.4, 5.5, 5.6, 7.0, 7.1)
- Nginx is reversed proxy of apache
- `autopilot` has access to `www-data`, `www-data` never ever able to access directly, all daily commands are done by `autopilot`
- All app located at `srv/users/autopilot/apps`

I have a deployment server without public ip, this able to SSH-ed to my apps server via internal ip. All Magallanes tasks are excuted from this server.

I assume now you understand why I hate the `use_sudo` ? Because it is really the top most security risk ever, which I'm upset to.

If you need to execute sudo to few commands, you can specified them in `/etc/sudoers.d/<your_deploy_user>`

```
<your_deploy_user> ALL=(ALL) NOPASSWD: /full/path/to/command
```

**Comment by DavidGarciaCat** [comment]
Hi @hectornguyen 

Please don't misunderstand my words, I completely understand the meaning of `security risk` when we need to use a user who has `sudo` permissions.

So, given the example above, I presume a suitable option for this case (deployment user `ubuntu` and web server user `www-data`) is to set the PHP-FPM Pool to `ubuntu` (because I need to run all `composer...` and other commands using this one) and then add the `ubuntu` user as part of the `www-data` system group, so in the end all files created by `www-data` user/group will be able to be managed/deleted by `ubuntu` user, right?

Cheers,

**Comment by hectornguyen** [comment]
@DavidGarciaCat please read my previous answer once again. Your solution is already there if you read it.
